// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_star = "CgkInYf8oN4PEAIQEw"; // <GPGSID>
        public const string achievement_hook_540 = "CgkInYf8oN4PEAIQCw"; // <GPGSID>
        public const string achievement_the_night_is_dark_and_full_of_terrors = "CgkInYf8oN4PEAIQBw"; // <GPGSID>
        public const string achievement_3_2_1_go = "CgkInYf8oN4PEAIQCA"; // <GPGSID>
        public const string achievement_that_was_easy = "CgkInYf8oN4PEAIQCQ"; // <GPGSID>
        public const string leaderboard_speedrun = "CgkInYf8oN4PEAIQAA"; // <GPGSID>
        public const string achievement_easy_like_sunday_morning = "CgkInYf8oN4PEAIQFA"; // <GPGSID>
        public const string achievement_hello_hook = "CgkInYf8oN4PEAIQBQ"; // <GPGSID>
        public const string achievement_hook_3040 = "CgkInYf8oN4PEAIQEA"; // <GPGSID>
        public const string achievement_hook_1540 = "CgkInYf8oN4PEAIQDQ"; // <GPGSID>
        public const string achievement_hook_4040 = "CgkInYf8oN4PEAIQEg"; // <GPGSID>
        public const string achievement_fast_like_the_flash = "CgkInYf8oN4PEAIQCg"; // <GPGSID>
        public const string achievement_hook_1040 = "CgkInYf8oN4PEAIQDA"; // <GPGSID>
        public const string achievement_hook_2540 = "CgkInYf8oN4PEAIQDw"; // <GPGSID>
        public const string leaderboard_highscore = "CgkInYf8oN4PEAIQBg"; // <GPGSID>
        public const string achievement_hook_2040 = "CgkInYf8oN4PEAIQDg"; // <GPGSID>
        public const string achievement_hook_3540 = "CgkInYf8oN4PEAIQEQ"; // <GPGSID>

}

